### ISSUE TITLE
Account not deployed. 

### ISSUE THREAD

**Issue by MiguelESP89** [586837r/node-red-contrib-alexa-remote2#30]
Hey i updated remote 2 and add the routine node and entered the proxy 
- This IP
- port: 3456
- auto init: on
- events: on
- service Host: layla.amazon.de
- page: amazon.de
- language: de-DE

but i get always a failure after saving the changes. 

I have the same issues with the cookie. 
Before updating it was working fine

![Bildschirmfoto 2019-07-29 um 10 31 11](https://user-images.githubusercontent.com/39128034/62033334-03766600-b1ec-11e9-9cf3-9647cbeb36e5.png)

Anyone who know whats wrong? 

Thank you 
Miguel

**Comment by 586837r** [comment]
The notification you get does not have anything to do with authentification. It just means that the account you selected in the routine node does not (yet) exist and because of that it couldn't load the routines for you to select in the *Execute Routine* option. 
What do you see in the node status? Is there a problem with the authentification? If so what do you see in the debug log? 
You can manually trigger an authentification with the *Alexa Init* to get an error.

**Comment by ThomasPoett** [comment]
I got it similar, but overcome it and ignored, but than this other issue I have opened now appears.
