### ISSUE TITLE
Smarthome "Query", "Get" incomplete

### ISSUE THREAD

**Issue by bwims** [586837r/node-red-contrib-alexa-remote2#62]
Using the Smarthome "Query" options, not all devices have the correct names and some do not appear. In particular, devices created by the Hardhill "Alexa Skills" contribution do not appear in the list.  This is unfortunate because that contrib can only run one instance per username, so checking state is only possible on one node.  The Hardhill devices DO appear in the "Action" list, however.

Smarthome "Get" "Devices" only returns groups and lambda bridge - not devices - which is a bit odd!

Smarthome "Get" "Entities" seems to be most accurate - if only it **also** contained the current state of the devices.

Lastly, is there a way to refresh the list of devices?  It would be nice to have a refresh button.

**Comment by 586837r** [comment]
In "Action" you will only see the devices that support at least 1 action. And in "Query" you will only see the devices that support at least 1 query property. The virtual devices created with Hardhill's Skill do not support any Query properties. But there is a fork of his skill and nodes that does: [node-red-contrib-alexa-smart-home](https://www.npmjs.com/package/node-red-contrib-alexa-smart-home).

"Get" "Devices" and "Get" "Entities" return a raw response from amazon. ("Get" "Devices" does contain devices deep inside).

"Get" "Simplified" should be the most straight forward. But it returns a Map instead of an Object so you need a function node like this to be able to view it in debug log: 
```
function map2obj(map){
    const obj = {};
    for(const [k,v] of map.entries()) obj[k] = v;
    return obj;
}
msg.payload = map2obj(msg.payload);
return msg;
```

To get the properties of a device you will have to use a Query. "Get" will only return you static information.

To refresh the list just trigger a new initialisation by triggering an "Alexa Init" node with "Initialise" option. A refresh button is not a bad idea...

**Comment by bwims** [comment]
Many thanks for the quick snd useful explanation!
