### ISSUE TITLE
no csrf found

### ISSUE THREAD

**Issue by AndreWohnsland** [586837r/node-red-contrib-alexa-remote2#95]
Version 3.8 with Node-Red Version 6.0.4

After signing/auth in with the proxy method and getting successfully the cookie, the node shows error "no csrf found".

After reinstalling node-red and the palettes I recreated the issue. At the first time, the authentication is successfully and I can select my device and the action. Once this is set and I deploy again I continuously get that error and it is not working.

**Comment by AndreWohnsland** [comment]
Resetting permission (read/write) in Node-Red fixed this issue for me. Closing

**Comment by Prog72** [comment]
Im having the same problem. Can you elaborate on what you mean by resetting permission?

**Comment by sigalou** [comment]
Everything worked fine on the first tests then I also get "no CRSF found"
![image](https://user-images.githubusercontent.com/26350534/74081485-cd922400-4a4f-11ea-8505-6761bc471c79.png)
I did a reset
![image](https://user-images.githubusercontent.com/26350534/74081493-daaf1300-4a4f-11ea-989a-ecd8a165bc09.png)
then an initialize
![image](https://user-images.githubusercontent.com/26350534/74081502-ffa38600-4a4f-11ea-9365-4f0b934f229c.png)
![image](https://user-images.githubusercontent.com/26350534/74081511-1d70eb00-4a50-11ea-85f5-6052d7f2d76a.png)
![image](https://user-images.githubusercontent.com/26350534/74081525-311c5180-4a50-11ea-8b3c-e908fca3dc6c.png)

**Comment by AndreWohnsland** [comment]
Depending on what platform you run Node-Red, this can differ. In my case, I run it in a docker container inside the hass.io container (Home Assistant on a Raspberry Pi, also in a docker). Inside the interface, you got the option to edit the configuration, by default **ssl** as well as **require_ssl** are set to true. I had only the first set to false but missed the second since Node-Red will start without any errors. If you are running Node-Red outside of the Home Assistant/ Hass.io environment this may differ. I think in this case it is important, that Node-Red got reading and writing permissions how you achieve this may differ, but I think you will find all the needed information in the documentation for each Node-Red installation.

**Comment by Prog72** [comment]
@AndreWohnsland Many thanks, I'll look into that.

**Comment by jcwren** [comment]
I'm running into the same issue. This was working, but no longer does. NodeRed is running on a Raspberry Pi 3. I deploy the flows, the control says to open 'nodered.private.com:3456'. I do, I sign in, it says it retrieved the cookie. The control then says 'no csrf found'.

If there's a permissions issue, then something isn't checking a return code and throwing an error correctly (maybe in alexa-cookie?). For testing, I made the home directory, .node-red directory and the file for the cookie all 0777 permissions (just for testing!). The file is never updated, presumably because the 'no csrf found' message means it didn't find something to make it write.
